 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 577-449-210
Traceback (most recent call last):
  File "/Users/aihoshino/debuggers/app.py", line 26, in <module>
    app.run(debug=True)
  File "/Users/aihoshino/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 662, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Users/aihoshino/Library/Python/3.9/lib/python/site-packages/werkzeug/serving.py", line 1115, in run_simple
    run_with_reloader(
  File "/Users/aihoshino/Library/Python/3.9/lib/python/site-packages/werkzeug/_reloader.py", line 459, in run_with_reloader
    ensure_echo_on()
  File "/Users/aihoshino/Library/Python/3.9/lib/python/site-packages/werkzeug/_reloader.py", line 439, in ensure_echo_on
    termios.tcsetattr(sys.stdin, termios.TCSANOW, attributes)
termios.error: (4, 'Interrupted system call')
